In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.0.0+cpu'

## Introduction to Tensor

### Creating Tensors

PyTorch tensor are create using torch.Tensor()

ref - https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
# Get Tensor back ans int
scaler.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7,8],
                      [6,5]])
MATRIX

tensor([[7, 8],
        [6, 5]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([6, 5])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                      [5,6,6],
                      [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [5, 6, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [5, 6, 6],
        [7, 8, 9]])

In [17]:
# Practice
TENSOR1 = torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]],
                     [[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
TENSOR1

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [18]:
TENSOR1.ndim

3

In [19]:
TENSOR1.shape

torch.Size([2, 3, 3])

### Random Tensor

Why Random Nos. ?

'Start with Random Numbers -> Look at Data -> Update Random Numbers -> Look at Data -> Update Random Numbers'

ref - https://pytorch.org/docs/stable/generated/torch.rand.html

In [20]:
# Create a random tensor of size(3,4)
random_tensor = torch.rand(3,4,3)
random_tensor

tensor([[[0.2008, 0.0916, 0.0533],
         [0.3940, 0.0559, 0.0460],
         [0.3238, 0.1037, 0.1935],
         [0.5235, 0.5911, 0.5219]],

        [[0.2837, 0.3918, 0.9483],
         [0.7936, 0.9932, 0.2679],
         [0.3710, 0.1581, 0.3809],
         [0.3224, 0.3812, 0.9434]],

        [[0.2841, 0.5409, 0.4287],
         [0.9522, 0.9049, 0.3037],
         [0.5380, 0.9408, 0.3845],
         [0.1807, 0.2235, 0.7375]]])

In [21]:
random_tensor.ndim

3

In [22]:
random_tensor.shape

torch.Size([3, 4, 3])

In [23]:
# Creating Random tensor similar to Image Shape
random_image_size_tensor =torch.rand(size=[224,224,3],) # height, width , color channels
random_image_size_tensor

tensor([[[0.5154, 0.2492, 0.5364],
         [0.5736, 0.5497, 0.2180],
         [0.3874, 0.7677, 0.2061],
         ...,
         [0.3602, 0.0254, 0.5001],
         [0.7088, 0.3364, 0.0927],
         [0.9359, 0.4917, 0.3001]],

        [[0.4328, 0.3107, 0.7053],
         [0.3173, 0.6037, 0.7513],
         [0.8771, 0.3718, 0.6707],
         ...,
         [0.8548, 0.1864, 0.3391],
         [0.0130, 0.0992, 0.2543],
         [0.9180, 0.1881, 0.4776]],

        [[0.3641, 0.1675, 0.8706],
         [0.4722, 0.0974, 0.9321],
         [0.2632, 0.3075, 0.1380],
         ...,
         [0.2322, 0.3079, 0.7471],
         [0.3796, 0.8172, 0.2493],
         [0.8187, 0.6566, 0.1346]],

        ...,

        [[0.2814, 0.1997, 0.7041],
         [0.1542, 0.6094, 0.2577],
         [0.0362, 0.7713, 0.9221],
         ...,
         [0.3716, 0.1759, 0.9662],
         [0.6526, 0.0399, 0.0308],
         [0.8369, 0.9635, 0.6310]],

        [[0.0465, 0.6989, 0.2015],
         [0.3722, 0.7630, 0.2797],
         [0.

In [24]:
random_image_size_tensor.ndim

3

In [25]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

### Zeroes and Ones

In [26]:
# Create a tenor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
zeros * torch.rand(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# Create tensor of all ones
ones = torch.ones(size=(3,4),dtype=int)
ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [29]:
ones.dtype

torch.int64

### Create a range of tensors and tensors-like

ref - https://pytorch.org/docs/stable/generated/torch.arange.html

In [30]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# Create tesnors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Tensor datatypes is one of the 3 big errors arrive in Pytorch

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not no right device

ref - https://pytorch.org/docs/stable/tensors.html

In [32]:
# Float 32 tensor
float_32_tensor =torch.tensor([3.0,6.0,9.0],
                             dtype=None, # what datatype of tensor (float32 etc)
                             device=None, #'cpu or gpu -> cuda'
                             requires_grad=False) # whether to track gradient
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.half()
# or
float_16_tensor = float_32_tensor.type(torch.float) # torch.half

In [35]:
float_16_tensor

tensor([3., 6., 9.])

In [36]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [37]:
int_32_tensor = torch.tensor([3,4,5],
                             dtype=torch.int32)

In [38]:
float_16_tensor * int_32_tensor

tensor([ 9., 24., 45.])

### Getting info from tensors (tensor attributes)
1. tensor not datatype - to check use tensor.dtype
2. tensor not right shape - to check use tensor.shape or tensor.size()
3. tensor not on right device - to check use tensor.device

In [39]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9834, 0.4516, 0.3892, 0.6251],
        [0.7974, 0.4992, 0.0196, 0.4572],
        [0.1350, 0.0559, 0.1701, 0.4828]])

In [40]:
print("Tensor Datatype :",some_tensor.dtype,
"Tensor Shape :",some_tensor.shape,
"Tensor Device :",some_tensor.device)

Tensor Datatype : torch.float32 Tensor Shape : torch.Size([3, 4]) Tensor Device : cpu


### Manipulating Tensors (Tensor Operations)
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication

In [41]:
# Create a tensor and add 10
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [42]:
# multiply
tensor * 10

tensor([10, 20, 30])

In [43]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [44]:
torch.mul(tensor,10)

tensor([10, 20, 30])