In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.0.0'

## Introduction to Tensor

### Creating Tensors

PyTorch tensor are create using torch.Tensor()

ref - https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
# Get Tensor back ans int
scaler.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7,8],
                      [6,5]])
MATRIX

tensor([[7, 8],
        [6, 5]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([6, 5])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                      [5,6,6],
                      [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [5, 6, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [5, 6, 6],
        [7, 8, 9]])

In [17]:
# Practice
TENSOR1 = torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]],
                     [[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
TENSOR1

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [18]:
TENSOR1.ndim

3

In [19]:
TENSOR1.shape

torch.Size([2, 3, 3])

### Random Tensor

Why Random Nos. ?

'Start with Random Numbers -> Look at Data -> Update Random Numbers -> Look at Data -> Update Random Numbers'

ref - https://pytorch.org/docs/stable/generated/torch.rand.html

In [20]:
# Create a random tensor of size(3,4)
random_tensor = torch.rand(3,4,3)
random_tensor

tensor([[[0.7811, 0.2357, 0.4046],
         [0.6839, 0.0901, 0.7057],
         [0.6060, 0.7512, 0.6922],
         [0.4719, 0.5205, 0.4999]],

        [[0.6698, 0.5535, 0.4190],
         [0.0070, 0.6186, 0.4008],
         [0.0452, 0.0583, 0.6005],
         [0.0101, 0.5705, 0.5337]],

        [[0.7206, 0.7205, 0.6253],
         [0.6279, 0.0577, 0.8319],
         [0.9314, 0.3629, 0.5101],
         [0.4437, 0.6941, 0.7607]]])

In [21]:
random_tensor.ndim

3

In [22]:
random_tensor.shape

torch.Size([3, 4, 3])

In [23]:
# Creating Random tensor similar to Image Shape
random_image_size_tensor = torch.rand(size=[224,224,3],) # height, width , color channels
random_image_size_tensor

tensor([[[0.3270, 0.2781, 0.8259],
         [0.3648, 0.6545, 0.4443],
         [0.9152, 0.9426, 0.8997],
         ...,
         [0.6555, 0.6841, 0.5782],
         [0.2953, 0.5574, 0.6966],
         [0.4858, 0.2953, 0.0779]],

        [[0.0547, 0.9882, 0.5122],
         [0.2748, 0.2633, 0.1872],
         [0.4696, 0.1552, 0.5558],
         ...,
         [0.6217, 0.6888, 0.2460],
         [0.2440, 0.1052, 0.2726],
         [0.0413, 0.0750, 0.3858]],

        [[0.7744, 0.4204, 0.6331],
         [0.8916, 0.2464, 0.6812],
         [0.4179, 0.3664, 0.5340],
         ...,
         [0.6600, 0.1106, 0.5359],
         [0.6764, 0.4506, 0.7219],
         [0.5497, 0.3284, 0.2220]],

        ...,

        [[0.9154, 0.4742, 0.5998],
         [0.8995, 0.7307, 0.1675],
         [0.1829, 0.4632, 0.8811],
         ...,
         [0.4538, 0.6238, 0.4994],
         [0.3986, 0.5136, 0.5987],
         [0.7995, 0.9591, 0.0600]],

        [[0.7085, 0.2800, 0.2770],
         [0.8727, 0.6767, 0.5534],
         [0.

In [24]:
random_image_size_tensor.ndim

3

In [25]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

### Zeroes and Ones

In [26]:
# Create a tenor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
zeros * torch.rand(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# Create tensor of all ones
ones = torch.ones(size=(3,4),dtype=int)
ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [29]:
ones.dtype

torch.int64

### Create a range of tensors and tensors-like

ref - https://pytorch.org/docs/stable/generated/torch.arange.html

In [30]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# Create tesnors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Tensor datatypes is one of the 3 big errors arrive in Pytorch

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not no right device

ref - https://pytorch.org/docs/stable/tensors.html

In [32]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                             dtype=None, # what datatype of tensor (float32 etc)
                             device=None, #'cpu or gpu -> cuda'
                             requires_grad=False) # whether to track gradient
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.half()
# or
float_16_tensor = float_32_tensor.type(torch.float) # torch.half

In [35]:
float_16_tensor

tensor([3., 6., 9.])

In [36]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [37]:
int_32_tensor = torch.tensor([3,4,5],
                             dtype=torch.int32)

In [38]:
float_16_tensor * int_32_tensor

tensor([ 9., 24., 45.])

### Getting info from tensors (tensor attributes)
1. tensor not datatype - to check use tensor.dtype
2. tensor not right shape - to check use tensor.shape or tensor.size()
3. tensor not on right device - to check use tensor.device

In [39]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9347, 0.8717, 0.8938, 0.0904],
        [0.6894, 0.9951, 0.3559, 0.0054],
        [0.6509, 0.1531, 0.5913, 0.2318]])

In [40]:
print("Tensor Datatype :",some_tensor.dtype,
"Tensor Shape :",some_tensor.shape,
"Tensor Device :",some_tensor.device)

Tensor Datatype : torch.float32 Tensor Shape : torch.Size([3, 4]) Tensor Device : cpu


### Manipulating Tensors (Tensor Operations)
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication

In [41]:
# Create a tensor and add 10
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [42]:
# multiply
tensor * 10

tensor([10, 20, 30])

In [43]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [44]:
# multiply using tensor function
torch.mul(tensor,10)

tensor([10, 20, 30])

### Matrix Multiplication

Two Main ways to multiply in tensors

1. Element-wise multipication or Cross Multiplication
2. Matrix multiplication or Dot Product

ref - https://www.mathsisfun.com/algebra/matrix-multiplying.html

Two Rules must Follow:
1. The **Inner Dimension** must match:
* '(3,2) @ (3,2)' wont work
* '(3,2) @ (2,3)' will work
* '(2,3) @ (3,2)' will work
2. Resulting matrix has dimension of **Outer Dimension**
* (2,3) @ (3,2) -> (2,2)
* (3,2) @ (2,3) -> (3,3)

In [45]:
torch.matmul(torch.rand(3,2) , torch.rand(2,3))

tensor([[0.4880, 0.2472, 0.4269],
        [0.1253, 0.3955, 0.5567],
        [0.9436, 0.8503, 1.3267]])

In [46]:
# Element wise multiplication
print(tensor, '*' , tensor)
print('Equals :', tensor * tensor )

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [47]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

### Shape Errors

In [48]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B =torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

#torch.mm(tensor_A,tensor_B) #(mm is alias for matmul)

To Fix Shape Issues, We can use Transpose 

A **Transpose** swithches axes or dimensions of given matrix

In [49]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [50]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [51]:
print(f'Initial shape for tensor A {tensor_A.shape} and for tensor B {tensor_B.shape}')
print(f'after transpose {tensor_B.T.shape}')
print(f'output : {torch.matmul(tensor_A,tensor_B.T)} and its shape is {torch.matmul(tensor_A,tensor_B.T).shape}')

Initial shape for tensor A torch.Size([3, 2]) and for tensor B torch.Size([3, 2])
after transpose torch.Size([2, 3])
output : tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]]) and its shape is torch.Size([3, 3])


## Finding Min. Max. Mean, Sum, etc (tensor aggregation)

In [52]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [53]:
# Min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [54]:
# Max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [55]:
# Mean
torch.mean(x.type(torch.float16)) , x.type(torch.float16).mean() , torch.mean(x,dtype=torch.float32)

(tensor(45., dtype=torch.float16),
 tensor(45., dtype=torch.float16),
 tensor(45.))

In [56]:
# Sum
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

## Finding Positinal min and max

In [57]:
x+1

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [58]:
# Position in tensor where minimum value exists
print('location : ',(x+1).argmin())
print('element at location : ',(x+1)[(x+1).argmin()])

location :  tensor(0)
element at location :  tensor(1)


In [59]:
# Position in tensor where maximum value exists
print('location : ',(x+1).argmax())
print('element at location : ',(x+1)[(x+1).argmax()])

location :  tensor(9)
element at location :  tensor(91)


## Reshaping, Stacking, Squeezing and Unsqueezing tensor

* Reshaping - reshapes input tensor to defined shape
* View - Returns a view of input tensor of certain shape but keeps same memory as original
* Stacking - Combine Multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - **removes one** dimension from tensor
* Unsqueeze - **adds one** dimension to tensor
* Permute - Reaturn a view of input with Dimension Permuted (swapped) in certain way 