In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.0.0'

## Introduction to Tensor

### Creating Tensors

PyTorch tensor are create using `torch.Tensor()`

ref -
* https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
# Get Tensor back ans int
scaler.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7,8],
                      [6,5]])
MATRIX

tensor([[7, 8],
        [6, 5]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([6, 5])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                      [5,6,6],
                      [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [5, 6, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [5, 6, 6],
        [7, 8, 9]])

In [17]:
# Practice
TENSOR1 = torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]],
                     [[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
TENSOR1

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [18]:
TENSOR1.ndim

3

In [19]:
TENSOR1.shape

torch.Size([2, 3, 3])

### Random Tensor

Why Random Nos. ?

`Start with Random Numbers -> Look at Data -> Update Random Numbers -> Look at Data -> Update Random Numbers`

ref -
* https://pytorch.org/docs/stable/generated/torch.rand.html

In [20]:
# Create a random tensor of size(3,4)
random_tensor = torch.rand(3,4,3)
random_tensor

tensor([[[0.0310, 0.1499, 0.5118],
         [0.8006, 0.3409, 0.5772],
         [0.0762, 0.3716, 0.6959],
         [0.4416, 0.8677, 0.3301]],

        [[0.3122, 0.7603, 0.7353],
         [0.2838, 0.4352, 0.8908],
         [0.1724, 0.0151, 0.8477],
         [0.7751, 0.0566, 0.0088]],

        [[0.2063, 0.9333, 0.3536],
         [0.4608, 0.5475, 0.8711],
         [0.2023, 0.3168, 0.0528],
         [0.5859, 0.3639, 0.7891]]])

In [21]:
random_tensor.ndim

3

In [22]:
random_tensor.shape

torch.Size([3, 4, 3])

In [23]:
# Creating Random tensor similar to Image Shape
random_image_size_tensor = torch.rand(size=[224,224,3],) # height, width , color channels
random_image_size_tensor

tensor([[[0.9857, 0.8959, 0.5738],
         [0.3369, 0.4041, 0.1294],
         [0.6896, 0.9524, 0.7589],
         ...,
         [0.8073, 0.2506, 0.5081],
         [0.9198, 0.1272, 0.9122],
         [0.8046, 0.2934, 0.4906]],

        [[0.6340, 0.9875, 0.0949],
         [0.5863, 0.6221, 0.2979],
         [0.9532, 0.2279, 0.2087],
         ...,
         [0.0932, 0.0093, 0.5605],
         [0.3192, 0.4071, 0.6805],
         [0.9070, 0.2448, 0.1918]],

        [[0.1186, 0.8888, 0.7820],
         [0.7810, 0.0280, 0.0764],
         [0.5687, 0.6927, 0.0094],
         ...,
         [0.3776, 0.6071, 0.1917],
         [0.1305, 0.5834, 0.6621],
         [0.0147, 0.8040, 0.3840]],

        ...,

        [[0.6658, 0.9669, 0.7036],
         [0.5801, 0.1902, 0.5147],
         [0.0487, 0.6557, 0.6701],
         ...,
         [0.5325, 0.8406, 0.7031],
         [0.2151, 0.9828, 0.8176],
         [0.3053, 0.2841, 0.9200]],

        [[0.1963, 0.9666, 0.3885],
         [0.1159, 0.7607, 0.7112],
         [0.

In [24]:
random_image_size_tensor.ndim

3

In [25]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

### Zeroes and Ones

In [26]:
# Create a tenor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
zeros * torch.rand(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# Create tensor of all ones
ones = torch.ones(size=(3,4),dtype=int)
ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [29]:
ones.dtype

torch.int64

### Create a range of tensors and tensors-like

ref -
* https://pytorch.org/docs/stable/generated/torch.arange.html

In [30]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# Create tesnors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Tensor datatypes is one of the 3 big errors arrive in Pytorch

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not no right device

ref -
* https://pytorch.org/docs/stable/tensors.html

In [32]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                             dtype=None, # what datatype of tensor (float32 etc)
                             device=None, #'cpu or gpu -> cuda'
                             requires_grad=False) # whether to track gradient
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.half()
# or
float_16_tensor = float_32_tensor.type(torch.float) # torch.half

In [35]:
float_16_tensor

tensor([3., 6., 9.])

In [36]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [37]:
int_32_tensor = torch.tensor([3,4,5],
                             dtype=torch.int32)

In [38]:
float_16_tensor * int_32_tensor

tensor([ 9., 24., 45.])

### Getting info from tensors (tensor attributes)
1. tensor not datatype - to check use tensor.dtype
2. tensor not right shape - to check use tensor.shape or tensor.size()
3. tensor not on right device - to check use tensor.device

In [39]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9105, 0.3577, 0.3549, 0.8397],
        [0.7855, 0.9017, 0.8440, 0.8826],
        [0.8142, 0.0227, 0.5957, 0.4844]])

In [40]:
print("Tensor Datatype :",some_tensor.dtype,
"Tensor Shape :",some_tensor.shape,
"Tensor Device :",some_tensor.device)

Tensor Datatype : torch.float32 Tensor Shape : torch.Size([3, 4]) Tensor Device : cpu


### Manipulating Tensors (Tensor Operations)
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication

In [41]:
# Create a tensor and add 10
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [42]:
# multiply
tensor * 10

tensor([10, 20, 30])

In [43]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [44]:
# multiply using tensor function
torch.mul(tensor,10)

tensor([10, 20, 30])

### Matrix Multiplication

Two Main ways to multiply in tensors

1. Element-wise multipication or Cross Multiplication
2. Matrix multiplication or Dot Product

ref -
* https://www.mathsisfun.com/algebra/matrix-multiplying.html

Two Rules must Follow:
1. The **Inner Dimension** must match:
* '(3,2) @ (3,2)' wont work
* '(3,2) @ (2,3)' will work
* '(2,3) @ (3,2)' will work
2. Resulting matrix has dimension of **Outer Dimension**
* (2,3) @ (3,2) -> (2,2)
* (3,2) @ (2,3) -> (3,3)

In [45]:
torch.matmul(torch.rand(3,2) , torch.rand(2,3))

tensor([[0.3921, 0.0489, 0.5682],
        [0.7346, 0.0915, 1.0647],
        [0.5598, 0.0648, 0.8406]])

In [46]:
# Element wise multiplication
print(tensor, '*' , tensor)
print('Equals :', tensor * tensor )

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [47]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

### Shape Errors

In [48]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B =torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

#torch.mm(tensor_A,tensor_B) #(mm is alias for matmul)

To Fix Shape Issues, We can use Transpose 

A **Transpose** swithches axes or dimensions of given matrix

In [49]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [50]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [51]:
print(f'Initial shape for tensor A {tensor_A.shape} and for tensor B {tensor_B.shape}')
print(f'after transpose {tensor_B.T.shape}')
print(f'output : {torch.matmul(tensor_A,tensor_B.T)} and its shape is {torch.matmul(tensor_A,tensor_B.T).shape}')

Initial shape for tensor A torch.Size([3, 2]) and for tensor B torch.Size([3, 2])
after transpose torch.Size([2, 3])
output : tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]]) and its shape is torch.Size([3, 3])


## Finding Min. Max. Mean, Sum, etc (tensor aggregation)

In [52]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [53]:
# Min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [54]:
# Max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [55]:
# Mean
torch.mean(x.type(torch.float16)) , x.type(torch.float16).mean() , torch.mean(x,dtype=torch.float32)

(tensor(45., dtype=torch.float16),
 tensor(45., dtype=torch.float16),
 tensor(45.))

In [56]:
# Sum
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

## Finding Positinal min and max

In [57]:
x+1

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [58]:
# Position in tensor where minimum value exists
print('location : ',(x+1).argmin())
print('element at location : ',(x+1)[(x+1).argmin()])

location :  tensor(0)
element at location :  tensor(1)


In [59]:
# Position in tensor where maximum value exists
print('location : ',(x+1).argmax())
print('element at location : ',(x+1)[(x+1).argmax()])

location :  tensor(9)
element at location :  tensor(91)


## Reshaping, Stacking, Squeezing and Unsqueezing tensor

* Reshaping - reshapes input tensor to defined shape
* View - Returns a view of input tensor of certain shape but keeps same memory as original
* Stacking - Combine Multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - **removes unit** dimension from tensor
* Unsqueeze - **adds one** dimension to tensor
* Permute - Reaturn a view of input with Dimension Permuted (swapped) in certain way 

In [60]:
# Create Tensor
x = torch.arange(1.,10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [61]:
# Add extra dimension
x_reshaped = x.reshape(9,1)
print(x.size())
print(x_reshaped)
print(x_reshaped.size())

torch.Size([9])
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
torch.Size([9, 1])


In [62]:
# Change View
z = x.view(3,3)
z, z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [63]:
# Changing z changes x because it shares same memory as original but doesnt affect the shape
z[:,0]=5
z, x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [64]:
# Stack tensors
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [65]:
# torch.squeeze() - removes all single dimensions from target tensor
print(f"Previouse tensor : {x_reshaped}")
print(f"Previoe shape : {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor : {x_squeezed}")
print(f"New Shape : {x_squeezed.shape}")



Previouse tensor : tensor([[5.],
        [2.],
        [3.],
        [5.],
        [5.],
        [6.],
        [5.],
        [8.],
        [9.]])
Previoe shape : torch.Size([9, 1])

New tensor : tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])
New Shape : torch.Size([9])


In [66]:
x_reshaped.squeeze()

tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])

In [67]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f"Previous target : {x_squeezed}")
print(f"Previous Shape : {x_squeezed.shape}")

# Adding dimension to x_reshaped
x_unsqueezed = x_squeezed.unsqueeze(dim=-0)
print(f"\nNew tensor : {x_unsqueezed}")
print(f"New Shape : {x_unsqueezed.shape}")

Previous target : tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])
Previous Shape : torch.Size([9])

New tensor : tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])
New Shape : torch.Size([1, 9])


In [68]:
# torch.permute - rearrages the dimension of a traget tensor in a specified order
x_original = torch.rand(size=(224,224,3)) 
print(f"Shape before Permute : {x_original.shape}") #[height, width, color_channel]

# Premute the original tensor to rearrage the axis
x_permuted = x_original.permute(2,0,1) # shifts axis 0 -> 1, 1 -> 2, 2 -> 0
print(f"Shape after Permute : {x_permuted.shape}") #[color_channel, height, width]

Shape before Permute : torch.Size([224, 224, 3])
Shape after Permute : torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)
Indexing is same as numpy

In [69]:
# Create a tensor
x= torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [70]:
# Indexing new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [71]:
# Index on middle bracket (dim=1)
x[0,1,1]

tensor(5)

In [72]:
# ":" to select all target dimension
x[:,0]

tensor([[1, 2, 3]])

In [73]:
# Practice
print(x[:,:,1])
print(x[0,0,:])
print(x[0,1,:])

tensor([[2, 5, 8]])
tensor([1, 2, 3])
tensor([4, 5, 6])


## Pytorch tensors & Numpy

Pytorch interacting with Numpy

* Convert data from Numpy to Tensor -> `torch.from_numpy(ndarray)`
* Convert data from Tensor to Numpy -> `torch.Tensor.numpy()`

In [74]:
# Numpy Array -> Tensor
import numpy as np
import torch

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32) # warning: when converting from numpy -> tensor, pytorch copies same datatype from numpy viz. float64 unless changed (default dtype of tensor is float32) 
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [75]:
print(array.dtype)
print(tensor.dtype)

float64
torch.float32


In [76]:
# Changing the value of array, does this affect tensor ?
array = array + 1
array,tensor
# NO

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [77]:
# Tensor -> Numpy array
tensor = torch.ones(7)
array = tensor.numpy() # datatype remains same as tensor's
tensor, array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [78]:
 # Changing the value of tensor, does this affect array ?
tensor = tensor + 1
tensor,array
# NO

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)
How Neural Network Work ?

` Start with random nos. -> tensor operation -> update random nos. to try and malke them better represntation of data -> repeat -> repeat -> repeat ...`

To reduce the randomness in Neural Network we use **Random Seed**.

Essentially whta random seed does is **flavour** the randomness.

ref - 
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

In [79]:
#  Create 2 tensors

random_tensor_A = torch.rand(4,3)
random_tensor_B = torch.rand(4,3)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.5170, 0.5150, 0.9309],
        [0.0901, 0.7216, 0.8252],
        [0.0771, 0.3199, 0.9617],
        [0.8120, 0.3538, 0.4236]])
tensor([[0.4475, 0.2074, 0.2857],
        [0.3076, 0.9464, 0.0844],
        [0.9948, 0.8627, 0.7993],
        [0.0283, 0.1520, 0.9666]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]])


In [80]:
# Random but reproducable tensors
import torch

# Set random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED) # Set the random seed every time we call rand function
random_tensor_C = torch.rand(4,3)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(4,3)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])


## Running tensors and Pytorch on GPU (Making it Faster)

Gpus = faster computation with Cuda and Nvidia hardware

### 1. Getting a GPU

1. Easiest is Google Colab and Kaggle