In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.0.0'

## Introduction to Tensor

### Creating Tensors

PyTorch tensor are create using torch.Tensor()

ref - https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
# Get Tensor back ans int
scaler.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7,8],
                      [6,5]])
MATRIX

tensor([[7, 8],
        [6, 5]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([6, 5])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                      [5,6,6],
                      [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [5, 6, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [5, 6, 6],
        [7, 8, 9]])

In [17]:
# Practice
TENSOR1 = torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]],
                     [[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
TENSOR1

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [18]:
TENSOR1.ndim

3

In [19]:
TENSOR1.shape

torch.Size([2, 3, 3])

### Random Tensor

Why Random Nos. ?

'Start with Random Numbers -> Look at Data -> Update Random Numbers -> Look at Data -> Update Random Numbers'

ref - https://pytorch.org/docs/stable/generated/torch.rand.html

In [20]:
# Create a random tensor of size(3,4)
random_tensor = torch.rand(3,4,3)
random_tensor

tensor([[[0.0883, 0.0956, 0.6607],
         [0.0527, 0.8565, 0.7997],
         [0.4787, 0.0465, 0.1614],
         [0.4859, 0.4994, 0.9311]],

        [[0.8992, 0.2468, 0.2283],
         [0.2708, 0.6827, 0.3598],
         [0.0323, 0.9223, 0.6666],
         [0.2759, 0.9689, 0.4293]],

        [[0.8121, 0.3494, 0.8236],
         [0.5759, 0.8877, 0.3913],
         [0.2384, 0.7087, 0.5895],
         [0.7704, 0.3248, 0.7620]]])

In [21]:
random_tensor.ndim

3

In [22]:
random_tensor.shape

torch.Size([3, 4, 3])

In [23]:
# Creating Random tensor similar to Image Shape
random_image_size_tensor = torch.rand(size=[224,224,3],) # height, width , color channels
random_image_size_tensor

tensor([[[0.4764, 0.3625, 0.8622],
         [0.2087, 0.7181, 0.3880],
         [0.7497, 0.9169, 0.1960],
         ...,
         [0.0257, 0.2590, 0.0218],
         [0.2742, 0.3657, 0.2996],
         [0.4427, 0.8379, 0.8632]],

        [[0.3464, 0.5116, 0.7955],
         [0.2652, 0.6318, 0.2698],
         [0.4117, 0.5737, 0.3414],
         ...,
         [0.1499, 0.6290, 0.9183],
         [0.8282, 0.4294, 0.1750],
         [0.8992, 0.5155, 0.6691]],

        [[0.5102, 0.0760, 0.3937],
         [0.5230, 0.2438, 0.1484],
         [0.1243, 0.4007, 0.8166],
         ...,
         [0.8775, 0.7728, 0.3404],
         [0.8418, 0.1260, 0.5529],
         [0.0873, 0.1241, 0.7541]],

        ...,

        [[0.1324, 0.0844, 0.0697],
         [0.2490, 0.8383, 0.1363],
         [0.8340, 0.6156, 0.7950],
         ...,
         [0.4641, 0.6088, 0.1003],
         [0.8388, 0.5632, 0.6924],
         [0.8707, 0.4841, 0.8562]],

        [[0.9587, 0.6320, 0.8098],
         [0.2680, 0.0389, 0.9578],
         [0.

In [24]:
random_image_size_tensor.ndim

3

In [25]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

### Zeroes and Ones

In [26]:
# Create a tenor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
zeros * torch.rand(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# Create tensor of all ones
ones = torch.ones(size=(3,4),dtype=int)
ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [29]:
ones.dtype

torch.int64

### Create a range of tensors and tensors-like

ref - https://pytorch.org/docs/stable/generated/torch.arange.html

In [30]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# Create tesnors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Tensor datatypes is one of the 3 big errors arrive in Pytorch

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not no right device

ref - https://pytorch.org/docs/stable/tensors.html

In [32]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                             dtype=None, # what datatype of tensor (float32 etc)
                             device=None, #'cpu or gpu -> cuda'
                             requires_grad=False) # whether to track gradient
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.half()
# or
float_16_tensor = float_32_tensor.type(torch.float) # torch.half

In [35]:
float_16_tensor

tensor([3., 6., 9.])

In [36]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [37]:
int_32_tensor = torch.tensor([3,4,5],
                             dtype=torch.int32)

In [38]:
float_16_tensor * int_32_tensor

tensor([ 9., 24., 45.])

### Getting info from tensors (tensor attributes)
1. tensor not datatype - to check use tensor.dtype
2. tensor not right shape - to check use tensor.shape or tensor.size()
3. tensor not on right device - to check use tensor.device

In [39]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8374, 0.0603, 0.8603, 0.7492],
        [0.4189, 0.4055, 0.3152, 0.8388],
        [0.0231, 0.5688, 0.4985, 0.0164]])

In [40]:
print("Tensor Datatype :",some_tensor.dtype,
"Tensor Shape :",some_tensor.shape,
"Tensor Device :",some_tensor.device)

Tensor Datatype : torch.float32 Tensor Shape : torch.Size([3, 4]) Tensor Device : cpu


### Manipulating Tensors (Tensor Operations)
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication

In [41]:
# Create a tensor and add 10
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [42]:
# multiply
tensor * 10

tensor([10, 20, 30])

In [43]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [44]:
# multiply using tensor function
torch.mul(tensor,10)

tensor([10, 20, 30])

### Matrix Multiplication

Two Main ways to multiply in tensors

1. Element-wise multipication or Cross Multiplication
2. Matrix multiplication or Dot Product

ref - https://www.mathsisfun.com/algebra/matrix-multiplying.html

Two Rules must Follow:
1. The **Inner Dimension** must match:
* '(3,2) @ (3,2)' wont work
* '(3,2) @ (2,3)' will work
* '(2,3) @ (3,2)' will work
2. Resulting matrix has dimension of **Outer Dimension**
* (2,3) @ (3,2) -> (2,2)
* (3,2) @ (2,3) -> (3,3)

In [45]:
torch.matmul(torch.rand(3,2) , torch.rand(2,3))

tensor([[0.7946, 0.5004, 0.7012],
        [0.9684, 0.5502, 0.7418],
        [1.3066, 0.7820, 1.0758]])

In [46]:
# Element wise multiplication
print(tensor, '*' , tensor)
print('Equals :', tensor * tensor )

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [47]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

### Shape Errors

In [48]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B =torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

#torch.mm(tensor_A,tensor_B) #(mm is alias for matmul)

To Fix Shape Issues, We can use Transpose 

A **Transpose** swithches axes or dimensions of given matrix

In [49]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [50]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [51]:
print(f'Initial shape for tensor A {tensor_A.shape} and for tensor B {tensor_B.shape}')
print(f'after transpose {tensor_B.T.shape}')
print(f'output : {torch.matmul(tensor_A,tensor_B.T)} and its shape is {torch.matmul(tensor_A,tensor_B.T).shape}')

Initial shape for tensor A torch.Size([3, 2]) and for tensor B torch.Size([3, 2])
after transpose torch.Size([2, 3])
output : tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]]) and its shape is torch.Size([3, 3])


## Finding Min. Max. Mean, Sum, etc (tensor aggregation)

In [52]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [53]:
# Min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [54]:
# Max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [55]:
# Mean
torch.mean(x.type(torch.float16)) , x.type(torch.float16).mean() , torch.mean(x,dtype=torch.float32)

(tensor(45., dtype=torch.float16),
 tensor(45., dtype=torch.float16),
 tensor(45.))

In [56]:
# Sum
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

## Finding Positinal min and max

In [57]:
x+1

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [58]:
# Position in tensor where minimum value exists
print('location : ',(x+1).argmin())
print('element at location : ',(x+1)[(x+1).argmin()])

location :  tensor(0)
element at location :  tensor(1)


In [59]:
# Position in tensor where maximum value exists
print('location : ',(x+1).argmax())
print('element at location : ',(x+1)[(x+1).argmax()])

location :  tensor(9)
element at location :  tensor(91)


## Reshaping, Stacking, Squeezing and Unsqueezing tensor

* Reshaping - reshapes input tensor to defined shape
* View - Returns a view of input tensor of certain shape but keeps same memory as original
* Stacking - Combine Multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - **removes unit** dimension from tensor
* Unsqueeze - **adds one** dimension to tensor
* Permute - Reaturn a view of input with Dimension Permuted (swapped) in certain way 

In [60]:
# Create Tensor
x = torch.arange(1.,10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [61]:
# Add extra dimension
x_reshaped = x.reshape(9,1)
print(x.size())
print(x_reshaped)
print(x_reshaped.size())

torch.Size([9])
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
torch.Size([9, 1])


In [62]:
# Change View
z = x.view(3,3)
z, z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [63]:
# Changing z changes x because it shares same memory as original but doesnt affect the shape
z[:,0]=5
z, x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [64]:
# Stack tensors
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [65]:
# torch.squeeze() - removes all single dimensions from target tensor
print(f"Previouse tensor : {x_reshaped}")
print(f"Previoe shape : {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor : {x_squeezed}")
print(f"New Shape : {x_squeezed.shape}")



Previouse tensor : tensor([[5.],
        [2.],
        [3.],
        [5.],
        [5.],
        [6.],
        [5.],
        [8.],
        [9.]])
Previoe shape : torch.Size([9, 1])

New tensor : tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])
New Shape : torch.Size([9])


In [66]:
x_reshaped.squeeze()

tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])

In [67]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f"Previous target : {x_squeezed}")
print(f"Previous Shape : {x_squeezed.shape}")

# Adding dimension to x_reshaped
x_unsqueezed = x_squeezed.unsqueeze(dim=-0)
print(f"\nNew tensor : {x_unsqueezed}")
print(f"New Shape : {x_unsqueezed.shape}")

Previous target : tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])
Previous Shape : torch.Size([9])

New tensor : tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])
New Shape : torch.Size([1, 9])
