In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.0.0'

## Introduction to Tensor

### Creating Tensors

PyTorch tensor are create using torch.Tensor()

ref - https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scaler
scaler=torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
# Get Tensor back ans int
scaler.item()

7

In [5]:
# Vector
vector =torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7,8],
                      [6,5]])
MATRIX

tensor([[7, 8],
        [6, 5]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([6, 5])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                      [5,6,6],
                      [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [5, 6, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [5, 6, 6],
        [7, 8, 9]])

In [17]:
# Practice
TENSOR1=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]],
                     [[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
TENSOR1

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [18]:
TENSOR1.ndim

3

In [19]:
TENSOR1.shape

torch.Size([2, 3, 3])

### Random Tensor

Why Random Nos. ?

'Start with Random Numbers -> Look at Data -> Update Random Numbers -> Look at Data -> Update Random Numbers'

ref - https://pytorch.org/docs/stable/generated/torch.rand.html

In [20]:
# Create a random tensor of size(3,4)
random_tensor =torch.rand(3,4,3)
random_tensor

tensor([[[0.6219, 0.6237, 0.9889],
         [0.6170, 0.1552, 0.4399],
         [0.2285, 0.9354, 0.1047],
         [0.4768, 0.1284, 0.8443]],

        [[0.5479, 0.1402, 0.0307],
         [0.9383, 0.1648, 0.2625],
         [0.1324, 0.1157, 0.8467],
         [0.6617, 0.9301, 0.7963]],

        [[0.3740, 0.9315, 0.7232],
         [0.5435, 0.0094, 0.8012],
         [0.3493, 0.3184, 0.6635],
         [0.8142, 0.6715, 0.6082]]])

In [21]:
random_tensor.ndim

3

In [22]:
random_tensor.shape

torch.Size([3, 4, 3])

In [23]:
# Creating Random tensor similar to Image Shape
random_image_size_tensor =torch.rand(size=[224,224,3],) # height, width , color channels
random_image_size_tensor

tensor([[[0.5354, 0.5898, 0.0217],
         [0.9699, 0.8476, 0.9369],
         [0.7453, 0.5689, 0.9875],
         ...,
         [0.9545, 0.9009, 0.9245],
         [0.7962, 0.0195, 0.2944],
         [0.9382, 0.5023, 0.4900]],

        [[0.5734, 0.4185, 0.6373],
         [0.5247, 0.0229, 0.0392],
         [0.7413, 0.6278, 0.5089],
         ...,
         [0.1250, 0.3595, 0.5114],
         [0.9211, 0.6376, 0.7300],
         [0.9204, 0.7313, 0.7280]],

        [[0.4240, 0.9916, 0.6509],
         [0.7713, 0.0856, 0.4282],
         [0.4519, 0.3128, 0.7474],
         ...,
         [0.1867, 0.2652, 0.4741],
         [0.5341, 0.9751, 0.1735],
         [0.3412, 0.9897, 0.5568]],

        ...,

        [[0.9563, 0.3037, 0.3257],
         [0.7798, 0.6048, 0.1608],
         [0.0238, 0.0442, 0.0278],
         ...,
         [0.4740, 0.5194, 0.0790],
         [0.2488, 0.1142, 0.9653],
         [0.7939, 0.4923, 0.5392]],

        [[0.3726, 0.7187, 0.3661],
         [0.0497, 0.7798, 0.3009],
         [0.

In [24]:
random_image_size_tensor.ndim

3

In [25]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])