In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.0.0'

## Introduction to Tensor

### Creating Tensors

PyTorch tensor are create using `torch.Tensor()`

ref - https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
# Get Tensor back ans int
scaler.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7,8],
                      [6,5]])
MATRIX

tensor([[7, 8],
        [6, 5]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([6, 5])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                      [5,6,6],
                      [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [5, 6, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [5, 6, 6],
        [7, 8, 9]])

In [17]:
# Practice
TENSOR1 = torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]],
                     [[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
TENSOR1

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [18]:
TENSOR1.ndim

3

In [19]:
TENSOR1.shape

torch.Size([2, 3, 3])

### Random Tensor

Why Random Nos. ?

'Start with Random Numbers -> Look at Data -> Update Random Numbers -> Look at Data -> Update Random Numbers'

ref - https://pytorch.org/docs/stable/generated/torch.rand.html

In [20]:
# Create a random tensor of size(3,4)
random_tensor = torch.rand(3,4,3)
random_tensor

tensor([[[0.5751, 0.3288, 0.4467],
         [0.6960, 0.6008, 0.6711],
         [0.0734, 0.8256, 0.8678],
         [0.2955, 0.4153, 0.2577]],

        [[0.4670, 0.3894, 0.6973],
         [0.9992, 0.5425, 0.1242],
         [0.4689, 0.6188, 0.2780],
         [0.2544, 0.2156, 0.4692]],

        [[0.5408, 0.1136, 0.4877],
         [0.0213, 0.5849, 0.3921],
         [0.7017, 0.6944, 0.5055],
         [0.3436, 0.4963, 0.8252]]])

In [21]:
random_tensor.ndim

3

In [22]:
random_tensor.shape

torch.Size([3, 4, 3])

In [23]:
# Creating Random tensor similar to Image Shape
random_image_size_tensor = torch.rand(size=[224,224,3],) # height, width , color channels
random_image_size_tensor

tensor([[[0.9319, 0.2758, 0.8620],
         [0.3610, 0.0245, 0.5440],
         [0.7213, 0.9526, 0.6086],
         ...,
         [0.5243, 0.6746, 0.7685],
         [0.7956, 0.1546, 0.6451],
         [0.0677, 0.0947, 0.8186]],

        [[0.6271, 0.6084, 0.7933],
         [0.1877, 0.5348, 0.5621],
         [0.1511, 0.2283, 0.9368],
         ...,
         [0.7002, 0.6380, 0.0455],
         [0.3435, 0.1677, 0.1192],
         [0.8116, 0.1465, 0.1455]],

        [[0.9786, 0.9959, 0.2630],
         [0.3685, 0.5075, 0.1171],
         [0.7713, 0.7847, 0.6445],
         ...,
         [0.2206, 0.2319, 0.6135],
         [0.7220, 0.7448, 0.7976],
         [0.7165, 0.9687, 0.3524]],

        ...,

        [[0.4418, 0.8363, 0.7188],
         [0.9436, 0.1595, 0.5139],
         [0.9357, 0.0857, 0.7813],
         ...,
         [0.5004, 0.2305, 0.2485],
         [0.0219, 0.2761, 0.7810],
         [0.6050, 0.3817, 0.3461]],

        [[0.4343, 0.8329, 0.8445],
         [0.1125, 0.0849, 0.4288],
         [0.

In [24]:
random_image_size_tensor.ndim

3

In [25]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

### Zeroes and Ones

In [26]:
# Create a tenor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
zeros * torch.rand(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# Create tensor of all ones
ones = torch.ones(size=(3,4),dtype=int)
ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [29]:
ones.dtype

torch.int64

### Create a range of tensors and tensors-like

ref - https://pytorch.org/docs/stable/generated/torch.arange.html

In [30]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# Create tesnors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Tensor datatypes is one of the 3 big errors arrive in Pytorch

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not no right device

ref - https://pytorch.org/docs/stable/tensors.html

In [32]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                             dtype=None, # what datatype of tensor (float32 etc)
                             device=None, #'cpu or gpu -> cuda'
                             requires_grad=False) # whether to track gradient
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.half()
# or
float_16_tensor = float_32_tensor.type(torch.float) # torch.half

In [35]:
float_16_tensor

tensor([3., 6., 9.])

In [36]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [37]:
int_32_tensor = torch.tensor([3,4,5],
                             dtype=torch.int32)

In [38]:
float_16_tensor * int_32_tensor

tensor([ 9., 24., 45.])

### Getting info from tensors (tensor attributes)
1. tensor not datatype - to check use tensor.dtype
2. tensor not right shape - to check use tensor.shape or tensor.size()
3. tensor not on right device - to check use tensor.device

In [39]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0211, 0.4709, 0.0897, 0.3044],
        [0.9328, 0.7326, 0.7740, 0.9731],
        [0.6106, 0.7471, 0.7769, 0.5116]])

In [40]:
print("Tensor Datatype :",some_tensor.dtype,
"Tensor Shape :",some_tensor.shape,
"Tensor Device :",some_tensor.device)

Tensor Datatype : torch.float32 Tensor Shape : torch.Size([3, 4]) Tensor Device : cpu


### Manipulating Tensors (Tensor Operations)
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication

In [41]:
# Create a tensor and add 10
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [42]:
# multiply
tensor * 10

tensor([10, 20, 30])

In [43]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [44]:
# multiply using tensor function
torch.mul(tensor,10)

tensor([10, 20, 30])

### Matrix Multiplication

Two Main ways to multiply in tensors

1. Element-wise multipication or Cross Multiplication
2. Matrix multiplication or Dot Product

ref - https://www.mathsisfun.com/algebra/matrix-multiplying.html

Two Rules must Follow:
1. The **Inner Dimension** must match:
* '(3,2) @ (3,2)' wont work
* '(3,2) @ (2,3)' will work
* '(2,3) @ (3,2)' will work
2. Resulting matrix has dimension of **Outer Dimension**
* (2,3) @ (3,2) -> (2,2)
* (3,2) @ (2,3) -> (3,3)

In [45]:
torch.matmul(torch.rand(3,2) , torch.rand(2,3))

tensor([[0.5075, 0.8000, 0.5385],
        [0.1297, 0.2400, 0.6803],
        [0.2502, 0.3859, 0.1343]])

In [46]:
# Element wise multiplication
print(tensor, '*' , tensor)
print('Equals :', tensor * tensor )

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [47]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

### Shape Errors

In [48]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B =torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

#torch.mm(tensor_A,tensor_B) #(mm is alias for matmul)

To Fix Shape Issues, We can use Transpose 

A **Transpose** swithches axes or dimensions of given matrix

In [49]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [50]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [51]:
print(f'Initial shape for tensor A {tensor_A.shape} and for tensor B {tensor_B.shape}')
print(f'after transpose {tensor_B.T.shape}')
print(f'output : {torch.matmul(tensor_A,tensor_B.T)} and its shape is {torch.matmul(tensor_A,tensor_B.T).shape}')

Initial shape for tensor A torch.Size([3, 2]) and for tensor B torch.Size([3, 2])
after transpose torch.Size([2, 3])
output : tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]]) and its shape is torch.Size([3, 3])


## Finding Min. Max. Mean, Sum, etc (tensor aggregation)

In [52]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [53]:
# Min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [54]:
# Max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [55]:
# Mean
torch.mean(x.type(torch.float16)) , x.type(torch.float16).mean() , torch.mean(x,dtype=torch.float32)

(tensor(45., dtype=torch.float16),
 tensor(45., dtype=torch.float16),
 tensor(45.))

In [56]:
# Sum
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

## Finding Positinal min and max

In [57]:
x+1

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [58]:
# Position in tensor where minimum value exists
print('location : ',(x+1).argmin())
print('element at location : ',(x+1)[(x+1).argmin()])

location :  tensor(0)
element at location :  tensor(1)


In [59]:
# Position in tensor where maximum value exists
print('location : ',(x+1).argmax())
print('element at location : ',(x+1)[(x+1).argmax()])

location :  tensor(9)
element at location :  tensor(91)


## Reshaping, Stacking, Squeezing and Unsqueezing tensor

* Reshaping - reshapes input tensor to defined shape
* View - Returns a view of input tensor of certain shape but keeps same memory as original
* Stacking - Combine Multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - **removes unit** dimension from tensor
* Unsqueeze - **adds one** dimension to tensor
* Permute - Reaturn a view of input with Dimension Permuted (swapped) in certain way 

In [60]:
# Create Tensor
x = torch.arange(1.,10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [61]:
# Add extra dimension
x_reshaped = x.reshape(9,1)
print(x.size())
print(x_reshaped)
print(x_reshaped.size())

torch.Size([9])
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
torch.Size([9, 1])


In [62]:
# Change View
z = x.view(3,3)
z, z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [63]:
# Changing z changes x because it shares same memory as original but doesnt affect the shape
z[:,0]=5
z, x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [64]:
# Stack tensors
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [65]:
# torch.squeeze() - removes all single dimensions from target tensor
print(f"Previouse tensor : {x_reshaped}")
print(f"Previoe shape : {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor : {x_squeezed}")
print(f"New Shape : {x_squeezed.shape}")



Previouse tensor : tensor([[5.],
        [2.],
        [3.],
        [5.],
        [5.],
        [6.],
        [5.],
        [8.],
        [9.]])
Previoe shape : torch.Size([9, 1])

New tensor : tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])
New Shape : torch.Size([9])


In [66]:
x_reshaped.squeeze()

tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])

In [67]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f"Previous target : {x_squeezed}")
print(f"Previous Shape : {x_squeezed.shape}")

# Adding dimension to x_reshaped
x_unsqueezed = x_squeezed.unsqueeze(dim=-0)
print(f"\nNew tensor : {x_unsqueezed}")
print(f"New Shape : {x_unsqueezed.shape}")

Previous target : tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])
Previous Shape : torch.Size([9])

New tensor : tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])
New Shape : torch.Size([1, 9])


In [68]:
# torch.permute - rearrages the dimension of a traget tensor in a specified order
x_original = torch.rand(size=(224,224,3)) 
print(f"Shape before Permute : {x_original.shape}") #[height, width, color_channel]

# Premute the original tensor to rearrage the axis
x_permuted = x_original.permute(2,0,1) # shifts axis 0 -> 1, 1 -> 2, 2 -> 0
print(f"Shape after Permute : {x_permuted.shape}") #[color_channel, height, width]

Shape before Permute : torch.Size([224, 224, 3])
Shape after Permute : torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)
Indexing is same as numpy

In [69]:
# Create a tensor
x= torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [70]:
# Indexing new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [71]:
# Index on middle bracket (dim=1)
x[0,1,1]

tensor(5)

In [72]:
# ":" to select all target dimension
x[:,0]

tensor([[1, 2, 3]])

In [73]:
# Practice
print(x[:,:,1])
print(x[0,0,:])
print(x[0,1,:])

tensor([[2, 5, 8]])
tensor([1, 2, 3])
tensor([4, 5, 6])


## Pytorch tensors & Numpy

Pytorch interacting with Numpy

* Convert data from Numpy to Tensor -> `torch.from_numpy(ndarray)`
* Convert data from Tensor to Numpy -> `torch.Tensor.numpy()`