In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.0.0'

## Introduction to Tensor

### Creating Tensors

PyTorch tensor are create using torch.Tensor()

ref - https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
# Get Tensor back ans int
scaler.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7,8],
                      [6,5]])
MATRIX

tensor([[7, 8],
        [6, 5]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([6, 5])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                      [5,6,6],
                      [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [5, 6, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [5, 6, 6],
        [7, 8, 9]])

In [17]:
# Practice
TENSOR1 = torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]],
                     [[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
TENSOR1

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [18]:
TENSOR1.ndim

3

In [19]:
TENSOR1.shape

torch.Size([2, 3, 3])

### Random Tensor

Why Random Nos. ?

'Start with Random Numbers -> Look at Data -> Update Random Numbers -> Look at Data -> Update Random Numbers'

ref - https://pytorch.org/docs/stable/generated/torch.rand.html

In [20]:
# Create a random tensor of size(3,4)
random_tensor = torch.rand(3,4,3)
random_tensor

tensor([[[0.2768, 0.7105, 0.8914],
         [0.5380, 0.5995, 0.7077],
         [0.4382, 0.0797, 0.9764],
         [0.7063, 0.3000, 0.0662]],

        [[0.0866, 0.6209, 0.8812],
         [0.0892, 0.4064, 0.2374],
         [0.6942, 0.9726, 0.9546],
         [0.6470, 0.5449, 0.3832]],

        [[0.5785, 0.8335, 0.3195],
         [0.8166, 0.7389, 0.3023],
         [0.3872, 0.6359, 0.9798],
         [0.5567, 0.5065, 0.5417]]])

In [21]:
random_tensor.ndim

3

In [22]:
random_tensor.shape

torch.Size([3, 4, 3])

In [23]:
# Creating Random tensor similar to Image Shape
random_image_size_tensor =torch.rand(size=[224,224,3],) # height, width , color channels
random_image_size_tensor

tensor([[[0.1698, 0.9091, 0.2561],
         [0.2594, 0.6232, 0.5521],
         [0.1136, 0.2022, 0.5239],
         ...,
         [0.3373, 0.8335, 0.3206],
         [0.2751, 0.7516, 0.1994],
         [0.4245, 0.9251, 0.8757]],

        [[0.9794, 0.5463, 0.6873],
         [0.7371, 0.3907, 0.2480],
         [0.4326, 0.5141, 0.5842],
         ...,
         [0.9191, 0.9088, 0.7765],
         [0.2498, 0.6190, 0.1731],
         [0.3192, 0.2207, 0.6341]],

        [[0.7915, 0.0609, 0.7821],
         [0.4499, 0.4564, 0.6530],
         [0.3367, 0.4945, 0.2738],
         ...,
         [0.0994, 0.0057, 0.4040],
         [0.4277, 0.0974, 0.8506],
         [0.8557, 0.2306, 0.7438]],

        ...,

        [[0.1688, 0.3634, 0.4174],
         [0.2643, 0.9297, 0.6189],
         [0.9621, 0.4887, 0.2773],
         ...,
         [0.5964, 0.0790, 0.9837],
         [0.1499, 0.9757, 0.8759],
         [0.9759, 0.3360, 0.7481]],

        [[0.4846, 0.9978, 0.7599],
         [0.0546, 0.9041, 0.1807],
         [0.

In [24]:
random_image_size_tensor.ndim

3

In [25]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

### Zeroes and Ones

In [26]:
# Create a tenor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
zeros * torch.rand(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# Create tensor of all ones
ones = torch.ones(size=(3,4),dtype=int)
ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [29]:
ones.dtype

torch.int64

### Create a range of tensors and tensors-like

ref - https://pytorch.org/docs/stable/generated/torch.arange.html

In [30]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# Create tesnors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Tensor datatypes is one of the 3 big errors arrive in Pytorch

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not no right device

ref - https://pytorch.org/docs/stable/tensors.html

In [32]:
# Float 32 tensor
float_32_tensor =torch.tensor([3.0,6.0,9.0],
                             dtype=None, # what datatype of tensor (float32 etc)
                             device=None, #'cpu or gpu -> cuda'
                             requires_grad=False) # whether to track gradient
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.half()
# or
float_16_tensor = float_32_tensor.type(torch.float) # torch.half

In [35]:
float_16_tensor

tensor([3., 6., 9.])

In [36]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [37]:
int_32_tensor = torch.tensor([3,4,5],
                             dtype=torch.int32)

In [38]:
float_16_tensor * int_32_tensor

tensor([ 9., 24., 45.])

### Getting info from tensors (tensor attributes)
1. tensor not datatype - to check use tensor.dtype
2. tensor not right shape - to check use tensor.shape or tensor.size()
3. tensor not on right device - to check use tensor.device

In [39]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5453, 0.6379, 0.6070, 0.1541],
        [0.8814, 0.3926, 0.7511, 0.8815],
        [0.8168, 0.8083, 0.5960, 0.5045]])

In [40]:
print("Tensor Datatype :",some_tensor.dtype,
"Tensor Shape :",some_tensor.shape,
"Tensor Device :",some_tensor.device)

Tensor Datatype : torch.float32 Tensor Shape : torch.Size([3, 4]) Tensor Device : cpu


### Manipulating Tensors (Tensor Operations)
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication

In [41]:
# Create a tensor and add 10
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [42]:
# multiply
tensor * 10

tensor([10, 20, 30])

In [43]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [44]:
# multiply using tensor function
torch.mul(tensor,10)

tensor([10, 20, 30])

### Matrix Multiplication

Two Main ways to multiply in tensors

1. Element-wise multipication or Cross Multiplication
2. Matrix multiplication or Dot Product

ref - https://www.mathsisfun.com/algebra/matrix-multiplying.html

Two Rules must Follow:
1. The **Inner Dimension** must match:
* '(3,2) @ (3,2)' wont work
* '(3,2) @ (2,3)' will work
* '(2,3) @ (3,2)' will work
2. Resulting matrix has dimension of **Outer Dimension**
* (2,3) @ (3,2) -> (2,2)
* (3,2) @ (2,3) -> (3,3)

In [45]:
torch.matmul(torch.rand(3,2) , torch.rand(2,3))

tensor([[0.1145, 0.1550, 0.0484],
        [0.6900, 0.9837, 0.3352],
        [0.4871, 0.6564, 0.2034]])

In [46]:
# Element wise multiplication
print(tensor, '*' , tensor)
print('Equals :', tensor * tensor )

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [47]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

### Shape Errors

In [48]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B =torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

#torch.mm(tensor_A,tensor_B) #(mm is alias for matmul)

To Fix Shape Issues, We can use Transpose 

A **Transpose** swithches axes or dimensions of given matrix

In [49]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [50]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [51]:
print(f'Initial shape for tensor A {tensor_A.shape} and for tensor B {tensor_B.shape}')
print(f'after transpose {tensor_B.T.shape}')
print(f'output : {torch.matmul(tensor_A,tensor_B.T)} and its shape is {torch.matmul(tensor_A,tensor_B.T).shape}')

Initial shape for tensor A torch.Size([3, 2]) and for tensor B torch.Size([3, 2])
after transpose torch.Size([2, 3])
output : tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]]) and its shape is torch.Size([3, 3])


## Finding Min. Max. Mean, Sum, etc (tensor aggregation)

In [52]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [53]:
# Min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [54]:
# Max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [55]:
# Mean
torch.mean(x.type(torch.float16)) , x.type(torch.float16).mean() , torch.mean(x,dtype=torch.float32)

(tensor(45., dtype=torch.float16),
 tensor(45., dtype=torch.float16),
 tensor(45.))

In [56]:
# Sum
torch.sum(x) , x.sum()

(tensor(450), tensor(450))