In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.0.0+cpu'

## Introduction to Tensor

### Creating Tensors

PyTorch tensor are create using torch.Tensor()

ref - https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
# Get Tensor back ans int
scaler.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7,8],
                      [6,5]])
MATRIX

tensor([[7, 8],
        [6, 5]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([6, 5])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                      [5,6,6],
                      [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [5, 6, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [5, 6, 6],
        [7, 8, 9]])

In [17]:
# Practice
TENSOR1 = torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]],
                     [[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
TENSOR1

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [18]:
TENSOR1.ndim

3

In [19]:
TENSOR1.shape

torch.Size([2, 3, 3])

### Random Tensor

Why Random Nos. ?

'Start with Random Numbers -> Look at Data -> Update Random Numbers -> Look at Data -> Update Random Numbers'

ref - https://pytorch.org/docs/stable/generated/torch.rand.html

In [20]:
# Create a random tensor of size(3,4)
random_tensor = torch.rand(3,4,3)
random_tensor

tensor([[[0.2513, 0.0360, 0.1426],
         [0.2258, 0.9669, 0.8006],
         [0.7470, 0.4899, 0.0539],
         [0.2040, 0.0537, 0.8059]],

        [[0.1349, 0.3289, 0.5174],
         [0.1926, 0.3658, 0.6268],
         [0.5230, 0.5545, 0.0055],
         [0.4382, 0.2643, 0.6703]],

        [[0.6637, 0.5062, 0.6207],
         [0.9560, 0.0146, 0.6557],
         [0.0441, 0.7939, 0.8182],
         [0.3635, 0.3221, 0.2865]]])

In [21]:
random_tensor.ndim

3

In [22]:
random_tensor.shape

torch.Size([3, 4, 3])

In [23]:
# Creating Random tensor similar to Image Shape
random_image_size_tensor =torch.rand(size=[224,224,3],) # height, width , color channels
random_image_size_tensor

tensor([[[0.1548, 0.0271, 0.5922],
         [0.7880, 0.0139, 0.7422],
         [0.0090, 0.2278, 0.7527],
         ...,
         [0.7519, 0.3898, 0.7100],
         [0.1197, 0.8039, 0.4309],
         [0.6979, 0.9063, 0.7396]],

        [[0.1469, 0.8781, 0.4776],
         [0.5780, 0.5257, 0.0761],
         [0.2308, 0.7305, 0.9422],
         ...,
         [0.9640, 0.0511, 0.7221],
         [0.1262, 0.4051, 0.3946],
         [0.2457, 0.8198, 0.6167]],

        [[0.1562, 0.5842, 0.3456],
         [0.5561, 0.3947, 0.2791],
         [0.8953, 0.0281, 0.0891],
         ...,
         [0.6577, 0.7408, 0.9511],
         [0.0512, 0.7714, 0.4425],
         [0.7382, 0.1204, 0.4028]],

        ...,

        [[0.9333, 0.4203, 0.1318],
         [0.2421, 0.2137, 0.4487],
         [0.4058, 0.0453, 0.7738],
         ...,
         [0.8381, 0.3195, 0.4574],
         [0.2893, 0.6382, 0.3462],
         [0.1806, 0.3162, 0.5687]],

        [[0.7948, 0.5048, 0.3864],
         [0.8915, 0.4898, 0.5467],
         [0.

In [24]:
random_image_size_tensor.ndim

3

In [25]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

### Zeroes and Ones

In [26]:
# Create a tenor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
zeros * torch.rand(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# Create tensor of all ones
ones = torch.ones(size=(3,4),dtype=int)
ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [29]:
ones.dtype

torch.int64

### Create a range of tensors and tensors-like

ref - https://pytorch.org/docs/stable/generated/torch.arange.html

In [30]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# Create tesnors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Tensor datatypes is one of the 3 big errors arrive in Pytorch

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not no right device

ref - https://pytorch.org/docs/stable/tensors.html

In [32]:
# Float 32 tensor
float_32_tensor =torch.tensor([3.0,6.0,9.0],
                             dtype=None, # what datatype of tensor (float32 etc)
                             device=None, #'cpu or gpu -> cuda'
                             requires_grad=False) # whether to track gradient
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.half()
# or
float_16_tensor = float_32_tensor.type(torch.float) # torch.half

In [35]:
float_16_tensor

tensor([3., 6., 9.])

In [36]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [37]:
int_32_tensor = torch.tensor([3,4,5],
                             dtype=torch.int32)

In [38]:
float_16_tensor * int_32_tensor

tensor([ 9., 24., 45.])

### Getting info from tensors (tensor attributes)
1. tensor not datatype - to check use tensor.dtype
2. tensor not right shape - to check use tensor.shape or tensor.size()
3. tensor not on right device - to check use tensor.device

In [39]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4882, 0.0401, 0.6594, 0.8345],
        [0.4844, 0.5947, 0.9397, 0.5870],
        [0.2012, 0.8844, 0.1691, 0.8914]])

In [40]:
print("Tensor Datatype :",some_tensor.dtype,
"Tensor Shape :",some_tensor.shape,
"Tensor Device :",some_tensor.device)

Tensor Datatype : torch.float32 Tensor Shape : torch.Size([3, 4]) Tensor Device : cpu


### Manipulating Tensors (Tensor Operations)
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication

In [41]:
# Create a tensor and add 10
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [42]:
# multiply
tensor * 10

tensor([10, 20, 30])

In [43]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [44]:
# multiply using tensor function
torch.mul(tensor,10)

tensor([10, 20, 30])

### Matrix Multiplication

Two Main ways to multiply in tensors

1. Element-wise multipication or Cross Multiplication
2. Matrix multiplication or Dot Product

ref - https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [45]:
# Element wise multiplication
print(tensor, '*' , tensor)
print('Equals :', tensor * tensor )

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [46]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)