In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.0.0'

## Introduction to Tensor

### Creating Tensors

PyTorch tensor are create using torch.Tensor()

ref - https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
# Get Tensor back ans int
scaler.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7,8],
                      [6,5]])
MATRIX

tensor([[7, 8],
        [6, 5]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([6, 5])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                      [5,6,6],
                      [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [5, 6, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [5, 6, 6],
        [7, 8, 9]])

In [17]:
# Practice
TENSOR1 = torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]],
                     [[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
TENSOR1

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [18]:
TENSOR1.ndim

3

In [19]:
TENSOR1.shape

torch.Size([2, 3, 3])

### Random Tensor

Why Random Nos. ?

'Start with Random Numbers -> Look at Data -> Update Random Numbers -> Look at Data -> Update Random Numbers'

ref - https://pytorch.org/docs/stable/generated/torch.rand.html

In [20]:
# Create a random tensor of size(3,4)
random_tensor = torch.rand(3,4,3)
random_tensor

tensor([[[0.7565, 0.9193, 0.0788],
         [0.3059, 0.9903, 0.1926],
         [0.8076, 0.3687, 0.4918],
         [0.0390, 0.1688, 0.5457]],

        [[0.0800, 0.5982, 0.4746],
         [0.3420, 0.1485, 0.0519],
         [0.9917, 0.6355, 0.1514],
         [0.3230, 0.5993, 0.3975]],

        [[0.3575, 0.8914, 0.5249],
         [0.2390, 0.2838, 0.1097],
         [0.6877, 0.0024, 0.7773],
         [0.7428, 0.9564, 0.3148]]])

In [21]:
random_tensor.ndim

3

In [22]:
random_tensor.shape

torch.Size([3, 4, 3])

In [23]:
# Creating Random tensor similar to Image Shape
random_image_size_tensor = torch.rand(size=[224,224,3],) # height, width , color channels
random_image_size_tensor

tensor([[[0.3654, 0.5870, 0.6432],
         [0.7225, 0.1927, 0.1713],
         [0.8138, 0.8941, 0.8385],
         ...,
         [0.4150, 0.4177, 0.7166],
         [0.0472, 0.9498, 0.8850],
         [0.5507, 0.9352, 0.2802]],

        [[0.8042, 0.8256, 0.9520],
         [0.4355, 0.0898, 0.5605],
         [0.5689, 0.8109, 0.2133],
         ...,
         [0.1314, 0.0728, 0.2932],
         [0.5617, 0.3219, 0.7986],
         [0.8740, 0.5009, 0.9250]],

        [[0.3705, 0.9202, 0.3773],
         [0.8570, 0.1370, 0.3225],
         [0.7181, 0.6510, 0.8627],
         ...,
         [0.3077, 0.1698, 0.7043],
         [0.4417, 0.1051, 0.3131],
         [0.5041, 0.9310, 0.6394]],

        ...,

        [[0.5261, 0.1189, 0.7199],
         [0.3426, 0.0641, 0.8687],
         [0.6303, 0.9884, 0.5525],
         ...,
         [0.8437, 0.6442, 0.7536],
         [0.6545, 0.2316, 0.3311],
         [0.7978, 0.0058, 0.9275]],

        [[0.8657, 0.8197, 0.3099],
         [0.1210, 0.8028, 0.2943],
         [0.

In [24]:
random_image_size_tensor.ndim

3

In [25]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

### Zeroes and Ones

In [26]:
# Create a tenor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
zeros * torch.rand(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# Create tensor of all ones
ones = torch.ones(size=(3,4),dtype=int)
ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [29]:
ones.dtype

torch.int64

### Create a range of tensors and tensors-like

ref - https://pytorch.org/docs/stable/generated/torch.arange.html

In [30]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# Create tesnors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Tensor datatypes is one of the 3 big errors arrive in Pytorch

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not no right device

ref - https://pytorch.org/docs/stable/tensors.html

In [32]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                             dtype=None, # what datatype of tensor (float32 etc)
                             device=None, #'cpu or gpu -> cuda'
                             requires_grad=False) # whether to track gradient
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.half()
# or
float_16_tensor = float_32_tensor.type(torch.float) # torch.half

In [35]:
float_16_tensor

tensor([3., 6., 9.])

In [36]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [37]:
int_32_tensor = torch.tensor([3,4,5],
                             dtype=torch.int32)

In [38]:
float_16_tensor * int_32_tensor

tensor([ 9., 24., 45.])

### Getting info from tensors (tensor attributes)
1. tensor not datatype - to check use tensor.dtype
2. tensor not right shape - to check use tensor.shape or tensor.size()
3. tensor not on right device - to check use tensor.device

In [39]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7262, 0.3262, 0.7475, 0.0432],
        [0.2001, 0.6663, 0.8701, 0.6230],
        [0.7220, 0.5241, 0.9072, 0.9378]])

In [40]:
print("Tensor Datatype :",some_tensor.dtype,
"Tensor Shape :",some_tensor.shape,
"Tensor Device :",some_tensor.device)

Tensor Datatype : torch.float32 Tensor Shape : torch.Size([3, 4]) Tensor Device : cpu


### Manipulating Tensors (Tensor Operations)
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication

In [41]:
# Create a tensor and add 10
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [42]:
# multiply
tensor * 10

tensor([10, 20, 30])

In [43]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [44]:
# multiply using tensor function
torch.mul(tensor,10)

tensor([10, 20, 30])

### Matrix Multiplication

Two Main ways to multiply in tensors

1. Element-wise multipication or Cross Multiplication
2. Matrix multiplication or Dot Product

ref - https://www.mathsisfun.com/algebra/matrix-multiplying.html

Two Rules must Follow:
1. The **Inner Dimension** must match:
* '(3,2) @ (3,2)' wont work
* '(3,2) @ (2,3)' will work
* '(2,3) @ (3,2)' will work
2. Resulting matrix has dimension of **Outer Dimension**
* (2,3) @ (3,2) -> (2,2)
* (3,2) @ (2,3) -> (3,3)

In [45]:
torch.matmul(torch.rand(3,2) , torch.rand(2,3))

tensor([[0.3321, 0.6695, 0.1682],
        [0.2558, 0.4277, 0.1436],
        [0.0987, 0.1817, 0.0527]])

In [46]:
# Element wise multiplication
print(tensor, '*' , tensor)
print('Equals :', tensor * tensor )

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [47]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

### Shape Errors

In [48]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B =torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

#torch.mm(tensor_A,tensor_B) #(mm is alias for matmul)

To Fix Shape Issues, We can use Transpose 

A **Transpose** swithches axes or dimensions of given matrix

In [49]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [50]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [51]:
print(f'Initial shape for tensor A {tensor_A.shape} and for tensor B {tensor_B.shape}')
print(f'after transpose {tensor_B.T.shape}')
print(f'output : {torch.matmul(tensor_A,tensor_B.T)} and its shape is {torch.matmul(tensor_A,tensor_B.T).shape}')

Initial shape for tensor A torch.Size([3, 2]) and for tensor B torch.Size([3, 2])
after transpose torch.Size([2, 3])
output : tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]]) and its shape is torch.Size([3, 3])


## Finding Min. Max. Mean, Sum, etc (tensor aggregation)

In [52]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [53]:
# Min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [54]:
# Max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [55]:
# Mean
torch.mean(x.type(torch.float16)) , x.type(torch.float16).mean() , torch.mean(x,dtype=torch.float32)

(tensor(45., dtype=torch.float16),
 tensor(45., dtype=torch.float16),
 tensor(45.))

In [56]:
# Sum
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

## Finding Positinal min and max

In [57]:
x+1

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [58]:
# Position in tensor where minimum value exists
print('location : ',(x+1).argmin())
print('element at location : ',(x+1)[(x+1).argmin()])

location :  tensor(0)
element at location :  tensor(1)


In [59]:
# Position in tensor where maximum value exists
print('location : ',(x+1).argmax())
print('element at location : ',(x+1)[(x+1).argmax()])

location :  tensor(9)
element at location :  tensor(91)


## Reshaping, Stacking, Squeezing and Unsqueezing tensor

* Reshaping - reshapes input tensor to defined shape
* View - Returns a view of input tensor of certain shape but keeps same memory as original
* Stacking - Combine Multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - **removes one** dimension from tensor
* Unsqueeze - **adds one** dimension to tensor
* Permute - Reaturn a view of input with Dimension Permuted (swapped) in certain way 

In [60]:
# Create Tensor
x = torch.arange(1.,10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [61]:
# Add extra dimension
x_reshaped = x.reshape(9,1)
print(x.size())
print(x_reshaped)
print(x_reshaped.size())

torch.Size([9])
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
torch.Size([9, 1])


In [62]:
# Change View
z = x.view(3,3)
z, z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [63]:
z[:,0]=5
z, x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))