In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.0.0'

## Introduction to Tensor

### Creating Tensors

PyTorch tensor are create using torch.Tensor()

ref - https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
# Get Tensor back ans int
scaler.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7,8],
                      [6,5]])
MATRIX

tensor([[7, 8],
        [6, 5]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([6, 5])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                      [5,6,6],
                      [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [5, 6, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [5, 6, 6],
        [7, 8, 9]])

In [17]:
# Practice
TENSOR1 = torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]],
                     [[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
TENSOR1

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [18]:
TENSOR1.ndim

3

In [19]:
TENSOR1.shape

torch.Size([2, 3, 3])

### Random Tensor

Why Random Nos. ?

'Start with Random Numbers -> Look at Data -> Update Random Numbers -> Look at Data -> Update Random Numbers'

ref - https://pytorch.org/docs/stable/generated/torch.rand.html

In [20]:
# Create a random tensor of size(3,4)
random_tensor = torch.rand(3,4,3)
random_tensor

tensor([[[0.2183, 0.4210, 0.4451],
         [0.8760, 0.7597, 0.9947],
         [0.9170, 0.4582, 0.8872],
         [0.5699, 0.5459, 0.5209]],

        [[0.3846, 0.9755, 0.9724],
         [0.8029, 0.3958, 0.7711],
         [0.1403, 0.3964, 0.0554],
         [0.3278, 0.6737, 0.1981]],

        [[0.8740, 0.6022, 0.7391],
         [0.3572, 0.5012, 0.3987],
         [0.2041, 0.1439, 0.4986],
         [0.5749, 0.0443, 0.2663]]])

In [21]:
random_tensor.ndim

3

In [22]:
random_tensor.shape

torch.Size([3, 4, 3])

In [23]:
# Creating Random tensor similar to Image Shape
random_image_size_tensor = torch.rand(size=[224,224,3],) # height, width , color channels
random_image_size_tensor

tensor([[[0.1953, 0.7277, 0.3575],
         [0.4433, 0.9426, 0.6784],
         [0.7684, 0.9558, 0.4039],
         ...,
         [0.3917, 0.2212, 0.7715],
         [0.2174, 0.4224, 0.6319],
         [0.9335, 0.9454, 0.9483]],

        [[0.9223, 0.6931, 0.1945],
         [0.1984, 0.2380, 0.3507],
         [0.0054, 0.7577, 0.2228],
         ...,
         [0.7959, 0.1889, 0.9169],
         [0.6034, 0.7606, 0.0922],
         [0.6943, 0.1189, 0.5715]],

        [[0.1371, 0.6947, 0.3575],
         [0.7536, 0.1333, 0.4128],
         [0.4877, 0.0241, 0.9041],
         ...,
         [0.2007, 0.3113, 0.0747],
         [0.6314, 0.7648, 0.2557],
         [0.4347, 0.7664, 0.2528]],

        ...,

        [[0.5417, 0.5178, 0.7108],
         [0.2367, 0.0146, 0.3901],
         [0.7933, 0.0647, 0.5025],
         ...,
         [0.3787, 0.2462, 0.8327],
         [0.0163, 0.4979, 0.0949],
         [0.8576, 0.8661, 0.5843]],

        [[0.9495, 0.2570, 0.4093],
         [0.3640, 0.6389, 0.0293],
         [0.

In [24]:
random_image_size_tensor.ndim

3

In [25]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

### Zeroes and Ones

In [26]:
# Create a tenor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
zeros * torch.rand(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# Create tensor of all ones
ones = torch.ones(size=(3,4),dtype=int)
ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [29]:
ones.dtype

torch.int64

### Create a range of tensors and tensors-like

ref - https://pytorch.org/docs/stable/generated/torch.arange.html

In [30]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# Create tesnors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Tensor datatypes is one of the 3 big errors arrive in Pytorch

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not no right device

ref - https://pytorch.org/docs/stable/tensors.html

In [32]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                             dtype=None, # what datatype of tensor (float32 etc)
                             device=None, #'cpu or gpu -> cuda'
                             requires_grad=False) # whether to track gradient
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.half()
# or
float_16_tensor = float_32_tensor.type(torch.float) # torch.half

In [35]:
float_16_tensor

tensor([3., 6., 9.])

In [36]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [37]:
int_32_tensor = torch.tensor([3,4,5],
                             dtype=torch.int32)

In [38]:
float_16_tensor * int_32_tensor

tensor([ 9., 24., 45.])

### Getting info from tensors (tensor attributes)
1. tensor not datatype - to check use tensor.dtype
2. tensor not right shape - to check use tensor.shape or tensor.size()
3. tensor not on right device - to check use tensor.device

In [39]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6871, 0.3288, 0.5374, 0.9700],
        [0.2403, 0.0521, 0.4416, 0.3447],
        [0.3826, 0.6274, 0.5599, 0.1556]])

In [40]:
print("Tensor Datatype :",some_tensor.dtype,
"Tensor Shape :",some_tensor.shape,
"Tensor Device :",some_tensor.device)

Tensor Datatype : torch.float32 Tensor Shape : torch.Size([3, 4]) Tensor Device : cpu


### Manipulating Tensors (Tensor Operations)
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication

In [41]:
# Create a tensor and add 10
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [42]:
# multiply
tensor * 10

tensor([10, 20, 30])

In [43]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [44]:
# multiply using tensor function
torch.mul(tensor,10)

tensor([10, 20, 30])

### Matrix Multiplication

Two Main ways to multiply in tensors

1. Element-wise multipication or Cross Multiplication
2. Matrix multiplication or Dot Product

ref - https://www.mathsisfun.com/algebra/matrix-multiplying.html

Two Rules must Follow:
1. The **Inner Dimension** must match:
* '(3,2) @ (3,2)' wont work
* '(3,2) @ (2,3)' will work
* '(2,3) @ (3,2)' will work
2. Resulting matrix has dimension of **Outer Dimension**
* (2,3) @ (3,2) -> (2,2)
* (3,2) @ (2,3) -> (3,3)

In [45]:
torch.matmul(torch.rand(3,2) , torch.rand(2,3))

tensor([[0.3749, 0.3746, 0.1209],
        [0.8692, 0.8725, 0.2822],
        [0.5820, 0.6591, 0.2271]])

In [46]:
# Element wise multiplication
print(tensor, '*' , tensor)
print('Equals :', tensor * tensor )

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [47]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

### Shape Errors

In [48]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B =torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

#torch.mm(tensor_A,tensor_B) #(mm is alias for matmul)

To Fix Shape Issues, We can use Transpose 

A **Transpose** swithches axes or dimensions of given matrix

In [49]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [50]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [51]:
print(f'Initial shape for tensor A {tensor_A.shape} and for tensor B {tensor_B.shape}')
print(f'after transpose {tensor_B.T.shape}')
print(f'output : {torch.matmul(tensor_A,tensor_B.T)} and its shape is {torch.matmul(tensor_A,tensor_B.T).shape}')

Initial shape for tensor A torch.Size([3, 2]) and for tensor B torch.Size([3, 2])
after transpose torch.Size([2, 3])
output : tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]]) and its shape is torch.Size([3, 3])


## Finding Min. Max. Mean, Sum, etc (tensor aggregation)

In [52]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [53]:
# Min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [54]:
# Max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [55]:
# Mean
torch.mean(x.type(torch.float16)) , x.type(torch.float16).mean() , torch.mean(x,dtype=torch.float32)

(tensor(45., dtype=torch.float16),
 tensor(45., dtype=torch.float16),
 tensor(45.))

In [56]:
# Sum
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

## Finding Positinal min and max

In [57]:
x+1

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [58]:
# Position in tensor where minimum value exists
print('location : ',(x+1).argmin())
print('element at location : ',(x+1)[(x+1).argmin()])

location :  tensor(0)
element at location :  tensor(1)


In [59]:
# Position in tensor where maximum value exists
print('location : ',(x+1).argmax())
print('element at location : ',(x+1)[(x+1).argmax()])

location :  tensor(9)
element at location :  tensor(91)


## Reshaping, Stacking, Squeezing and Unsqueezing tensor

* Reshaping - reshapes input tensor to defined shape
* View - Returns a view of input tensor of certain shape but keeps same memory as original
* Stacking - Combine Multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - **removes unit** dimension from tensor
* Unsqueeze - **adds one** dimension to tensor
* Permute - Reaturn a view of input with Dimension Permuted (swapped) in certain way 

In [60]:
# Create Tensor
x = torch.arange(1.,10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [61]:
# Add extra dimension
x_reshaped = x.reshape(9,1)
print(x.size())
print(x_reshaped)
print(x_reshaped.size())

torch.Size([9])
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
torch.Size([9, 1])


In [62]:
# Change View
z = x.view(3,3)
z, z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [63]:
# Changing z changes x because it shares same memory as original but doesnt affect the shape
z[:,0]=5
z, x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [64]:
# Stack tensors
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [65]:
# torch.squeeze() - removes all single dimensions from target tensor
print(f"Previouse tensor : {x_reshaped}")
print(f"Previoe shape : {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor : {x_squeezed}")
print(f"New Shape : {x_squeezed.shape}")



Previouse tensor : tensor([[5.],
        [2.],
        [3.],
        [5.],
        [5.],
        [6.],
        [5.],
        [8.],
        [9.]])
Previoe shape : torch.Size([9, 1])

New tensor : tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])
New Shape : torch.Size([9])


In [66]:
x_reshaped.squeeze()

tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])

In [67]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f"Previous target : {x_squeezed}")
print(f"Previous Shape : {x_squeezed.shape}")

# Adding dimension to x_reshaped
x_unsqueezed = x_squeezed.unsqueeze(dim=-0)
print(f"\nNew tensor : {x_unsqueezed}")
print(f"New Shape : {x_unsqueezed.shape}")

Previous target : tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])
Previous Shape : torch.Size([9])

New tensor : tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])
New Shape : torch.Size([1, 9])


In [68]:
# torch.permute - rearrages the dimension of a traget tensor in a specified order
