In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.0.0'

## Introduction to Tensor

### Creating Tensors

PyTorch tensor are create using torch.Tensor()

In [2]:
# Scaler
scaler=torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
# Get Tensor back ans int
scaler.item()

7

In [5]:
# Vector
vector =torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
matrix = torch.tensor([[7,8],
                      [6,5]])
matrix

tensor([[7, 8],
        [6, 5]])

In [9]:
matrix.ndim

2

In [10]:
matrix[0]

tensor([7, 8])

In [11]:
matrix[1]

tensor([6, 5])

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
# Tensor
tensor = torch.tensor([[[1,2,3],
                      [5,6,6],
                      [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [5, 6, 6],
         [7, 8, 9]]])

In [14]:
tensor.ndim

3

In [15]:
tensor.shape

torch.Size([1, 3, 3])

In [16]:
tensor[0]

tensor([[1, 2, 3],
        [5, 6, 6],
        [7, 8, 9]])

In [17]:
# Practice
tensor1=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]],
                     [[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
tensor1

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [18]:
tensor1.ndim

3

In [19]:
tensor1.shape

torch.Size([2, 3, 3])