In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.0.0'

## Introduction to Tensor

### Creating Tensors

PyTorch tensor are create using torch.Tensor()

ref - https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
# Get Tensor back ans int
scaler.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7,8],
                      [6,5]])
MATRIX

tensor([[7, 8],
        [6, 5]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([6, 5])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                      [5,6,6],
                      [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [5, 6, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [5, 6, 6],
        [7, 8, 9]])

In [17]:
# Practice
TENSOR1 = torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]],
                     [[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
TENSOR1

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [18]:
TENSOR1.ndim

3

In [19]:
TENSOR1.shape

torch.Size([2, 3, 3])

### Random Tensor

Why Random Nos. ?

'Start with Random Numbers -> Look at Data -> Update Random Numbers -> Look at Data -> Update Random Numbers'

ref - https://pytorch.org/docs/stable/generated/torch.rand.html

In [20]:
# Create a random tensor of size(3,4)
random_tensor = torch.rand(3,4,3)
random_tensor

tensor([[[0.0708, 0.8580, 0.1173],
         [0.4191, 0.5553, 0.5309],
         [0.8871, 0.6303, 0.4445],
         [0.8663, 0.3251, 0.5680]],

        [[0.2490, 0.1616, 0.0539],
         [0.3122, 0.6760, 0.7693],
         [0.3681, 0.0504, 0.4324],
         [0.3335, 0.5414, 0.6828]],

        [[0.5768, 0.2076, 0.0137],
         [0.4305, 0.8642, 0.6345],
         [0.0924, 0.4623, 0.3413],
         [0.5680, 0.4154, 0.6544]]])

In [21]:
random_tensor.ndim

3

In [22]:
random_tensor.shape

torch.Size([3, 4, 3])

In [23]:
# Creating Random tensor similar to Image Shape
random_image_size_tensor =torch.rand(size=[224,224,3],) # height, width , color channels
random_image_size_tensor

tensor([[[0.1423, 0.1792, 0.4138],
         [0.9544, 0.7355, 0.4797],
         [0.2110, 0.5780, 0.1216],
         ...,
         [0.8622, 0.7688, 0.7305],
         [0.9806, 0.9149, 0.1577],
         [0.2469, 0.5920, 0.8386]],

        [[0.8218, 0.6479, 0.6089],
         [0.0504, 0.5044, 0.2676],
         [0.4792, 0.6985, 0.2103],
         ...,
         [0.4332, 0.5992, 0.1270],
         [0.5711, 0.7100, 0.2412],
         [0.3920, 0.8332, 0.5765]],

        [[0.7575, 0.0062, 0.3495],
         [0.0833, 0.6927, 0.6115],
         [0.5226, 0.8577, 0.3747],
         ...,
         [0.6073, 0.3737, 0.5695],
         [0.6313, 0.2186, 0.6944],
         [0.7332, 0.7705, 0.9186]],

        ...,

        [[0.6496, 0.3399, 0.5961],
         [0.0109, 0.8447, 0.4955],
         [0.3576, 0.5366, 0.8030],
         ...,
         [0.5823, 0.2026, 0.8556],
         [0.3335, 0.9168, 0.1740],
         [0.6455, 0.9328, 0.7810]],

        [[0.9960, 0.7324, 0.1995],
         [0.7595, 0.1918, 0.8960],
         [0.

In [24]:
random_image_size_tensor.ndim

3

In [25]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

### Zeroes and Ones

In [26]:
# Create a tenor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
zeros * torch.rand(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# Create tensor of all ones
ones = torch.ones(size=(3,4),dtype=int)
ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [29]:
ones.dtype

torch.int64

### Create a range of tensors and tensors-like

ref - https://pytorch.org/docs/stable/generated/torch.arange.html

In [30]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# Create tesnors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])