In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.0.0'

## Introduction to Tensor

### Creating Tensors

PyTorch tensor are create using torch.Tensor()

ref - https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
# Get Tensor back ans int
scaler.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7,8],
                      [6,5]])
MATRIX

tensor([[7, 8],
        [6, 5]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([6, 5])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                      [5,6,6],
                      [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [5, 6, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [5, 6, 6],
        [7, 8, 9]])

In [17]:
# Practice
TENSOR1 = torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]],
                     [[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
TENSOR1

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [18]:
TENSOR1.ndim

3

In [19]:
TENSOR1.shape

torch.Size([2, 3, 3])

### Random Tensor

Why Random Nos. ?

'Start with Random Numbers -> Look at Data -> Update Random Numbers -> Look at Data -> Update Random Numbers'

ref - https://pytorch.org/docs/stable/generated/torch.rand.html

In [20]:
# Create a random tensor of size(3,4)
random_tensor = torch.rand(3,4,3)
random_tensor

tensor([[[0.6370, 0.4817, 0.1973],
         [0.7411, 0.3894, 0.8081],
         [0.3966, 0.7773, 0.8295],
         [0.5075, 0.1718, 0.3033]],

        [[0.2768, 0.6430, 0.9554],
         [0.2847, 0.1130, 0.8371],
         [0.2741, 0.2584, 0.7820],
         [0.9244, 0.1480, 0.9642]],

        [[0.2355, 0.7790, 0.6867],
         [0.9550, 0.1890, 0.1896],
         [0.5871, 0.9180, 0.3087],
         [0.7590, 0.4675, 0.7595]]])

In [21]:
random_tensor.ndim

3

In [22]:
random_tensor.shape

torch.Size([3, 4, 3])

In [23]:
# Creating Random tensor similar to Image Shape
random_image_size_tensor =torch.rand(size=[224,224,3],) # height, width , color channels
random_image_size_tensor

tensor([[[3.5920e-02, 5.7988e-01, 4.0478e-01],
         [4.7883e-01, 8.0702e-01, 1.7125e-01],
         [1.5837e-03, 1.4752e-01, 2.1079e-01],
         ...,
         [7.5741e-01, 9.9011e-01, 2.5436e-01],
         [1.9813e-01, 3.4573e-01, 2.6344e-01],
         [9.7548e-01, 6.7113e-01, 5.9412e-01]],

        [[8.2991e-01, 2.0920e-02, 6.8373e-01],
         [7.6573e-01, 2.1517e-03, 5.8362e-01],
         [4.1083e-01, 9.2109e-01, 2.2290e-02],
         ...,
         [6.7724e-01, 2.2530e-01, 1.0429e-01],
         [6.2446e-01, 5.2472e-01, 7.3499e-01],
         [2.5955e-01, 2.6316e-01, 8.4098e-01]],

        [[1.0582e-02, 9.2756e-01, 3.5409e-01],
         [8.8985e-01, 7.0761e-01, 4.4812e-01],
         [1.3710e-01, 8.2610e-01, 2.8194e-01],
         ...,
         [1.9272e-01, 9.9285e-01, 6.1192e-01],
         [6.9234e-01, 6.9074e-01, 2.8551e-02],
         [9.2756e-01, 4.3823e-01, 5.8652e-01]],

        ...,

        [[1.8738e-01, 4.7442e-01, 9.0163e-01],
         [6.8762e-01, 7.9142e-01, 8.2623e-01]

In [24]:
random_image_size_tensor.ndim

3

In [25]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

### Zeroes and Ones

In [26]:
# Create a tenor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
zeros * torch.rand(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# Create tensor of all ones
ones = torch.ones(size=(3,4),dtype=int)
ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [29]:
ones.dtype

torch.int64

### Create a range of tensors and tensors-like

ref - https://pytorch.org/docs/stable/generated/torch.arange.html

In [30]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# Create tesnors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])