# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
random_tensor_a = torch.rand((7,7),device='cuda')
random_tensor_a

tensor([[0.3957, 0.2895, 0.8025, 0.8485, 0.8650, 0.7348, 0.3785],
        [0.9732, 0.9097, 0.3885, 0.2012, 0.7642, 0.1792, 0.5069],
        [0.9151, 0.1034, 0.4230, 0.3223, 0.0670, 0.8819, 0.5026],
        [0.0285, 0.0143, 0.4479, 0.7341, 0.7119, 0.7489, 0.7681],
        [0.8751, 0.2836, 0.6432, 0.0441, 0.9577, 0.5117, 0.2699],
        [0.9745, 0.0911, 0.2269, 0.8980, 0.3589, 0.5720, 0.1937],
        [0.9526, 0.8219, 0.8718, 0.7474, 0.2856, 0.4797, 0.4450]],
       device='cuda:0')

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
random_tensor_b = torch.rand((1,7),device='cuda')
# Perform matrix multiplication 
torch.matmul(random_tensor_b , random_tensor_a)

tensor([[2.5147, 1.2128, 1.8931, 1.6592, 1.9395, 1.7942, 1.1309]],
       device='cuda:0')

In [4]:
torch.matmul(random_tensor_a , random_tensor_b.T)

tensor([[1.8510],
        [2.0392],
        [1.5843],
        [1.4837],
        [2.0382],
        [1.4723],
        [1.9139]], device='cuda:0')

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_manual_seed_a = torch.rand(7,7)

# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_manual_seed_b = torch.rand(1,7)

# Matrix multiply tensors
torch.matmul(tensor_manual_seed_a,tensor_manual_seed_b.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [7]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()

# Create two random tensors on GPU
tensor_a = torch.rand((2,3)).to('cuda')
print(tensor_a)
tensor_b = torch.rand((2,3)).to('cuda')
print(tensor_b)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [8]:
# Perform matmul on tensor_A and tensor_B
result = torch.matmul(tensor_a, tensor_b.T)
print(result)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [9]:
# Find max
print(result.max())
# Find min
print(result.min())

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [10]:
# Find arg max
print(result.argmax())

# Find arg min
print(result.argmin())

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [11]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_random = torch.rand([1,1,1,10])
print(tensor_random, tensor_random.shape)

# Remove single dimensions
squeezd_tensor = tensor_random.squeeze()

# Print out tensors and their shapes
print(squeezd_tensor, squeezd_tensor.shape )

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
